src/ScanburSandbox/ViewModels/ScanClime/ScanClimeIndexVM.cs
using ScanburSandbox.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScanburSandbox.ViewModels.ScanClime
{
    public class ScanClimeIndexVM
    {
        public ScanClimeUnit Scunit {get; set; }
        public Measurement Measurement { get; set; }
        public List<ScanClimeUnit> AllUnitIds { get; set; }
    }
}

src/ScanburSandbox/ViewModels/ScanClime/ScanClimeListVM.cs
using ScanburSandbox.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScanburSandbox.ViewModels.ScanClime
{
    public class ScanClimeListVM
    {
        public List<ScanClimeUnit> Scunits {get; set; }
    
    }
}

src/ScanburSandbox/Controllers/ScanClimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ScanburSandbox.Models;
using ScanburSandbox.ViewModels.ScanClime;
using ScanburSandbox.Facades;

namespace ScanburSandbox.Controllers
{
    
    public class ScanClimeController : Controller
    {

        private Facade fac = Facade.Instance;

        public IActionResult Index(Guid? id)
        {
            using(var db = fac.NewDbContext)
            {
                ScanClimeUnit scu;
                if (id == null )
                {
                    scu = fac.ScanClimeUnitFac.GetFirst(db);
                    this.RedirectToAction("Index", new { id = scu.Id });
                } else
                {
                    scu = fac.ScanClimeUnitFac.GetOrFail(db, id); 
                }
                var ms = Facade.Instance.MeasurementFc.Get(db,scu.CurrentMeasurementId); 
                return View(new ScanClimeIndexVM() { Scunit = scu, Measurement = ms, AllUnitIds = fac.ScanClimeUnitFac.GetAll(db) }); 
            }
        }

        public IActionResult List()
        {
            using(var db = Facade.Instance.NewDbContext)
            {
                var scunits = db.ScanClimeUnits.ToList();
                return View(new ScanClimeListVM() {
                    Scunits = scunits
                });
            }
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();

        }


        private static ApplicationDbContext GetDb()
        {
            return new ApplicationDbContext();
        }

        


    }
}

src/ScanburSandbox/Views/ScanClime/Index.cshtml
@model ScanClimeIndexVM
@{
    ViewData["Title"] = "Unit Dashboard";

    Layout = "_SdmLayout";
}

     

<div flex="">
    <div layout="row">
        <div flex><i title="No errors" style="color:green;font-size:200%" class="material-icons">done</i></div> <div flex class="small">GM500</div> 
    </div>
    <div >
        @if (Model.Measurement.PressureDiff > 0)
        {
            <i style="color:black;font-size:300%" class="material-icons" title="Positive air pressure">add circle outline</i>
        }
        else {
            <i style="color:black;font-size:300%" class="material-icons" title="Negative air pressure">remove circle outline</i>
        }
    </div>
    <div>
        <br /><br /><br /><br />
        <div class="large">@Math.Round(Model.Measurement.InletTemperature??0,1) &#176;C</div>
        <div class="small">
            Current temperature
        </div>
    </div>
    <div>
        <br /><br /><br /><br />
        <div class="large"> @Math.Round(Model.Measurement.CageHumidity??0, 1) RH%</div>
        <div class="small">
            Current humidity
        </div>
    </div>

    <div>
        <br /><br /><br /><br />
        <!-- TODO: Find a better way to implement formating in views -->
        <div class="large"> @Math.Round(Model.Measurement.AirChangeActual??0, 0)</div>
        <div class="small">
            Air changes pr. hour
        </div>
    </div>
</div>
<div flex="75">
    <div layout="column">
        <div flex class="border-bottom">
            <div layout="row">
                <div flex class="">
                @Model.Scunit.Title
                </div>
                <div flex class="small"></div>
                <div flex class="small" style="text-align:right" title="Time of last measurement">@Model.Measurement.UpdatedAt.ToShortTimeString()</div>

            </div>
        </div>
        <div flex style="white-space:nowrap" class="border-bottom">
            <div style="background-color:lightblue;width:40em;height:10em;text-align:center;vertical-align:middle" class="small">...temperature chart to come...</div>

        </div>
        <div flex style="white-space:nowrap">

            <div style="background-color:lightblue;width:40em;height:10em;text-align:center;vertical-align:middle" class="small">...humidity chart to come...</div>

        </div>
    </div>
</div>

src/ScanburSandbox/Views/ScanClime/List.cshtml
@model ScanClimeListVM
@{
    ViewData["Title"] = "List";

    Layout = "_SdmLayout";

}

@foreach (var sc in @Model.Scunits)
{
    <div style="display:inline-flex;width:50em;height:20em;text-align:center;vertical-align:middle; border-left:1px solid lightgrey;border-bottom:1px solid lightgrey;">
        <table>
            <tr>
                <td>
                    <h1 class="md-headline">
                        <a href='@Url.Action("Index","ScanClime",new { id = sc.Id})'>
                            @sc.Title
                        </a>
                    </h1>
                    <a href='@Url.Action("Index","ScanClime",new { id = sc.Id})'>

                        <span class="small">@sc.IdStr</span> &nbsp; <span class="small">Last updated: @sc.UpdatedAt</span>
                    </a>
                </td>
                <td>
                </td>
            </tr>
        </table>

    </div>
}